"""add document_text_fts search index

Revision ID: 08c778ee32af
Revises: 15160ee5686e
Create Date: 2026-08-01 04:03:04.707225

Hand-written, not autogenerated -- SQLAlchemy has no ORM construct for
FTS5 virtual tables or the triggers that keep them in sync with their
content table, so this is raw SQL. See docs/PHASE_2_PLAN.md §4/§11.1
(approved decision: triggers, not explicit application-level reindex,
for this specific table -- extraction is document_pages' only writer).

`document_text_fts` is an external-content FTS5 table: it doesn't store
its own copy of the text, just an index, with `content_rowid='page_id'`
pointing back at document_pages (page_id is that table's INTEGER PRIMARY
KEY, which SQLite treats as its rowid). Every search result therefore
resolves directly to a real document_pages row -- and from there, to a
specific document_id + page_number -- never to orphaned or duplicated text.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '08c778ee32af'
down_revision: Union[str, None] = '15160ee5686e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE VIRTUAL TABLE document_text_fts USING fts5(
            extracted_text,
            ocr_text,
            content='document_pages',
            content_rowid='page_id'
        )
        """
    )

    # Backfill any document_pages rows that already exist -- a vault
    # upgraded from Step 1 may already have extracted documents, and the
    # index must not silently start empty for them. (This is exactly the
    # class of bug the Step 1 migration had before its server_default fix:
    # forgetting that a migration can run against non-empty data.)
    op.execute(
        """
        INSERT INTO document_text_fts(rowid, extracted_text, ocr_text)
        SELECT page_id, extracted_text, ocr_text FROM document_pages
        """
    )

    op.execute(
        """
        CREATE TRIGGER document_pages_fts_ai AFTER INSERT ON document_pages BEGIN
            INSERT INTO document_text_fts(rowid, extracted_text, ocr_text)
            VALUES (new.page_id, new.extracted_text, new.ocr_text);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER document_pages_fts_ad AFTER DELETE ON document_pages BEGIN
            INSERT INTO document_text_fts(document_text_fts, rowid, extracted_text, ocr_text)
            VALUES ('delete', old.page_id, old.extracted_text, old.ocr_text);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER document_pages_fts_au AFTER UPDATE ON document_pages BEGIN
            INSERT INTO document_text_fts(document_text_fts, rowid, extracted_text, ocr_text)
            VALUES ('delete', old.page_id, old.extracted_text, old.ocr_text);
            INSERT INTO document_text_fts(rowid, extracted_text, ocr_text)
            VALUES (new.page_id, new.extracted_text, new.ocr_text);
        END
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS document_pages_fts_au")
    op.execute("DROP TRIGGER IF EXISTS document_pages_fts_ad")
    op.execute("DROP TRIGGER IF EXISTS document_pages_fts_ai")
    op.execute("DROP TABLE IF EXISTS document_text_fts")
