"""add extraction core: document_pages and citations

Revision ID: 15160ee5686e
Revises: 79c226771ac3
Create Date: 2026-08-01 03:35:15.856590
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15160ee5686e'
down_revision: Union[str, None] = '79c226771ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_pages',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('needs_ocr', sa.Boolean(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('page_id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_document_page_number')
    )
    op.create_table('citations',
    sa.Column('citation_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('quoted_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.page_id'], ),
    sa.PrimaryKeyConstraint('citation_id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_text_layer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('needs_ocr', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('ocr_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('extraction_status', sa.String(length=20), server_default='pending', nullable=False))
        batch_op.add_column(sa.Column('extraction_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('extraction_error')
        batch_op.drop_column('extraction_status')
        batch_op.drop_column('ocr_status')
        batch_op.drop_column('needs_ocr')
        batch_op.drop_column('has_text_layer')
        batch_op.drop_column('page_count')

    op.drop_table('citations')
    op.drop_table('document_pages')
    # ### end Alembic commands ###
