"""initial schema

Revision ID: 15aec3ba1e28
Revises: 
Create Date: 2026-07-30 04:04:15.393157
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15aec3ba1e28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('document_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('document_version_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('current_document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_path', sa.String(length=1000), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_date_precision', sa.String(length=20), nullable=True),
    sa.Column('document_date_source', sa.String(length=20), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ingested_by', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_group_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('is_current_version', sa.Boolean(), nullable=False),
    sa.Column('supersedes_document_id', sa.Integer(), nullable=True),
    sa.Column('version_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.type_id'], ),
    sa.ForeignKeyConstraint(['supersedes_document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['version_group_id'], ['document_version_groups.group_id'], ),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('case_id', 'sha256_hash', name='uq_document_case_hash')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_sha256_hash'), ['sha256_hash'], unique=False)
        batch_op.create_index('uq_one_current_version_per_group', ['version_group_id'], unique=True, sqlite_where=sa.text('is_current_version = 1'))

    op.create_table('document_custody_events',
    sa.Column('custody_event_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('sha256_hash_at_event', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes_at_event', sa.Integer(), nullable=False),
    sa.Column('storage_location_at_event', sa.String(length=1000), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('custody_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_custody_events')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('uq_one_current_version_per_group', sqlite_where=sa.text('is_current_version = 1'))
        batch_op.drop_index(batch_op.f('ix_documents_sha256_hash'))

    op.drop_table('documents')
    op.drop_table('document_version_groups')
    op.drop_table('audit_log')
    op.drop_table('document_types')
    op.drop_table('cases')
    # ### end Alembic commands ###
