"""add communication_text_fts search index

Revision ID: 34b632653500
Revises: eb9a3291e2e9
Create Date: 2026-08-14 16:24:59.553221

Hand-written, not autogenerated -- same reason as `document_text_fts`
(08c778ee32af) and `annotation_notes_fts` (d93ac0658fac): SQLAlchemy has
no ORM construct for FTS5 virtual tables. Additive only -- neither of
those two existing indexes, nor any other table, is touched.

`communication_text_fts` is a new, independent index over `communications`
(subject + parsed plain-text body only, per docs/COMMUNICATIONS_PLAN.md
Step 6) -- deliberately not merged into `document_text_fts`, so a
Communications search result can never be ambiguous with a Document
search result, the same reasoning `annotation_notes_fts` was kept
separate for. External-content, with `content_rowid='communication_id'`
pointing back at `communications`.

Sync strategy: triggers, unconditional delete-then-insert on every
UPDATE -- exactly `document_pages_fts_au`'s pattern (`08c778ee32af`), not
a `WHEN`-guarded variant. An earlier draft of this migration tried to
skip indexing soft-deleted rows (`WHEN new.deleted_at IS NULL` on insert,
two separate `WHEN`-guarded triggers for update) to keep the FTS5 index
itself "clean." That corrupts FTS5's internal index: reproduced directly
against a throwaway in-memory SQLite database, an UPDATE that doesn't
even touch `subject`/`body_text` (e.g. only `thread_id` changing, from
`app/core/communications/thread_rebuild.py`) silently broke `MATCH` for
that row afterward -- `SELECT ... FROM communication_text_fts` (a plain
content-table passthrough) still showed the correct text, but `MATCH`
found nothing, with no error raised at any point. Combining the delete
and insert into a single trigger body, unconditionally, exactly like
`document_pages_fts_au`, does not corrupt the index. Every row is
therefore always indexed regardless of `deleted_at`; excluding a
soft-deleted communication from a search result is instead the query's
job (`app/core/indexing/communications_search.py`'s
`c.deleted_at IS NULL` condition) -- the same division of responsibility
Document search already uses for `documents.deleted_at`.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '34b632653500'
down_revision: Union[str, None] = 'eb9a3291e2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE VIRTUAL TABLE communication_text_fts USING fts5(
            subject,
            body_text,
            content='communications',
            content_rowid='communication_id'
        )
        """
    )

    # Backfill any communications that already exist (a vault upgraded
    # from Step 3 may already have imported emails) -- every row,
    # unconditionally; a soft-deleted one is excluded at query time, not
    # by omitting it from the index (see module docstring).
    op.execute(
        """
        INSERT INTO communication_text_fts(rowid, subject, body_text)
        SELECT communication_id, subject, body_text FROM communications
        """
    )

    op.execute(
        """
        CREATE TRIGGER communications_fts_ai AFTER INSERT ON communications BEGIN
            INSERT INTO communication_text_fts(rowid, subject, body_text)
            VALUES (new.communication_id, new.subject, new.body_text);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER communications_fts_ad AFTER DELETE ON communications BEGIN
            INSERT INTO communication_text_fts(communication_text_fts, rowid, subject, body_text)
            VALUES ('delete', old.communication_id, old.subject, old.body_text);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER communications_fts_au AFTER UPDATE ON communications BEGIN
            INSERT INTO communication_text_fts(communication_text_fts, rowid, subject, body_text)
            VALUES ('delete', old.communication_id, old.subject, old.body_text);
            INSERT INTO communication_text_fts(rowid, subject, body_text)
            VALUES (new.communication_id, new.subject, new.body_text);
        END
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS communications_fts_au")
    op.execute("DROP TRIGGER IF EXISTS communications_fts_ad")
    op.execute("DROP TRIGGER IF EXISTS communications_fts_ai")
    op.execute("DROP TABLE IF EXISTS communication_text_fts")
