"""add annotation_notes_fts search index

Revision ID: d93ac0658fac
Revises: cd54e558e0d8
Create Date: 2026-08-01 05:00:00.000000

Hand-written, not autogenerated -- same reason as `document_text_fts`
(08c778ee32af): SQLAlchemy has no ORM construct for FTS5 virtual tables.

Unlike `document_text_fts`, this index has **no sync triggers** -- per
docs/PHASE_2_PLAN.md §4/§11.1 (approved decision 1): annotations are
written from more UI actions than `document_pages` ever is (highlight,
note, bookmark creation; soft-delete removal), so keeping this index in
sync is done via explicit application-level reindex calls instead of a
wide trigger surface -- see app/core/indexing/notes_search.py and its call
sites in app/core/annotations/service.py.

`annotation_notes_fts` is still an external-content FTS5 table (doesn't
store its own copy of the text, just an index), with
`content_rowid='annotation_id'` pointing back at `annotations`. Kept
entirely separate from `document_text_fts` so a search result can never be
ambiguous between "found in the source document" and "found in your own
notes about it" (docs/PHASE_2_PLAN.md §6/§7/§12.4).
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd93ac0658fac'
down_revision: Union[str, None] = 'cd54e558e0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE VIRTUAL TABLE annotation_notes_fts USING fts5(
            body_text,
            content='annotations',
            content_rowid='annotation_id'
        )
        """
    )

    # Backfill any annotations that already exist (a vault upgraded from
    # Step 4 may already have notes/bookmarks) -- only non-deleted rows
    # with actual body text; a highlight has none, and a removed note must
    # not become searchable the moment this migration runs.
    op.execute(
        """
        INSERT INTO annotation_notes_fts(rowid, body_text)
        SELECT annotation_id, body_text FROM annotations
        WHERE body_text IS NOT NULL AND deleted_at IS NULL
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS annotation_notes_fts")
